# -*- coding: utf-8 -*-
"""PCA , K-Means , GMM..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPqlFj5LRvhRqJCgp_enLH9zVNnJFlDV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, homogeneity_score, completeness_score, v_measure_score

# Load dataset
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('winequality-red.csv')

# Simpan kolom quality untuk analisis nanti, tapi tidak digunakan dalam clustering
df_hidden = df.drop(columns=["quality"], errors='ignore')

# Standarisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_hidden)

# Reduksi dimensi ke 2 atau 3 untuk visualisasi
pca = PCA(n_components=2)  # Bisa disesuaikan dengan jumlah fitur
X_pca = pca.fit_transform(X_scaled)

# Cek variansi yang dijelaskan oleh PCA
explained_variance = pca.explained_variance_ratio_
print(f"Variansi yang dijelaskan PCA: {explained_variance.sum():.4f}")

# Tentukan jumlah klaster optimal (misalnya 3)
n_clusters = 6
kmeans = KMeans(n_clusters=n_clusters, init='k-means++', random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_pca)

# Cek distribusi cluster K-Means
print(pd.Series(kmeans_labels).value_counts())

# Terapkan GMM berdasarkan hasil K-Means
gmm = GaussianMixture(n_components=n_clusters, covariance_type='full', random_state=42)
gmm_labels = gmm.fit_predict(X_pca)

# Cek distribusi cluster GMM
print(pd.Series(gmm_labels).value_counts())

# Evaluasi Silhouette Score
silhouette = silhouette_score(X_pca, gmm_labels)
print(f"Silhouette Score: {silhouette:.4f}")

# Evaluasi Davies-Bouldin Index
db_index = davies_bouldin_score(X_pca, gmm_labels)
print(f"Davies-Bouldin Index: {db_index:.4f}")

# Evaluasi Homogeneity, Completeness, dan V-Measure
homogeneity = homogeneity_score(kmeans_labels, gmm_labels)
completeness = completeness_score(kmeans_labels, gmm_labels)
v_measure = v_measure_score(kmeans_labels, gmm_labels)

print(f"Homogeneity Score: {homogeneity:.4f}")
print(f"Completeness Score: {completeness:.4f}")
print(f"V-Measure Score: {v_measure:.4f}")

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=gmm_labels, cmap='viridis', alpha=0.6, edgecolors='k')
plt.title("PCA + K-Means + GMM Clustering")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# Pastikan hasil klasterisasi sudah tersedia
df["Cluster"] = kmeans_labels  # atau gmm_labels jika menggunakan GMM
df["Original Class"] = df["quality"]  # Pastikan kelas asli tidak dihapus sebelumnya

# Perbandingan Klaster vs Kelas Asli menggunakan Cross Tabulation
comparison_table = pd.crosstab(df["Cluster"], df["Original Class"])
print("\nPerbandingan Klaster dengan Kelas Asli:")
print(comparison_table)

# Visualisasi Distribusi Klaster vs Kelas Asli
plt.figure(figsize=(10, 6))
sns.heatmap(comparison_table, annot=True, cmap="Blues", fmt="d")
plt.title("Perbandingan Klaster dengan Kelas Asli")
plt.xlabel("Kelas Asli")
plt.ylabel("Klaster")
plt.show()

# Evaluasi Hasil Klasterisasi dengan ARI & NMI
ari_score = adjusted_rand_score(df["Original Class"], df["Cluster"])
nmi_score = normalized_mutual_info_score(df["Original Class"], df["Cluster"])

print(f"\nAdjusted Rand Index (ARI): {ari_score:.4f}")
print(f"Normalized Mutual Information (NMI): {nmi_score:.4f}")

# Relabeling Klaster agar sesuai dengan kelas asli
relabel_map = {}
for cluster in range(6):  # Jumlah klaster = 6
    mode_label = df.loc[df["Cluster"] == cluster, "Original Class"].mode()[0]
    relabel_map[cluster] = mode_label

df["Relabeled Cluster"] = df["Cluster"].map(relabel_map)

# Evaluasi Setelah Relabeling
ari_relabel = adjusted_rand_score(df["Original Class"], df["Relabeled Cluster"])
nmi_relabel = normalized_mutual_info_score(df["Original Class"], df["Relabeled Cluster"])

print(f"\nSetelah Relabeling:")
print(f"Adjusted Rand Index (ARI): {ari_relabel:.4f}")
print(f"Normalized Mutual Information (NMI): {nmi_relabel:.4f}")

import numpy as np
import pandas as pd
from scipy.stats import mode
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# Load dataset
df = pd.read_csv("winequality-red.csv")  # Gantilah dengan path dataset yang benar

# Ambil fitur untuk klasterisasi
X = df.drop(columns=["quality"])  # Pastikan 'quality' adalah kolom kelas asli
true_labels = df["quality"].values  # Simpan label asli

# Standarisasi fitur
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Klasterisasi dengan K-Means
k = 6  # Jumlah klaster yang diinginkan
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_scaled)

# Klasterisasi dengan Gaussian Mixture Model (GMM)
gmm = GaussianMixture(n_components=k, random_state=42)
gmm_labels = gmm.fit_predict(X_scaled)

# Fungsi untuk relabeling berdasarkan mode kelas asli
from scipy.stats import mode

def relabel_clusters(true_labels, cluster_labels):
    new_labels = np.zeros_like(cluster_labels)
    unique_clusters = np.unique(cluster_labels)

    for cluster in unique_clusters:
        mask = cluster_labels == cluster
        if np.any(mask):
            new_labels[mask] = mode(true_labels[mask], keepdims=True).mode[0]  # Fix

    return new_labels

# Evaluasi sebelum relabeling
ari_before_kmeans = adjusted_rand_score(true_labels, kmeans_labels)
nmi_before_kmeans = normalized_mutual_info_score(true_labels, kmeans_labels)
print(f"K-Means Sebelum Relabeling - ARI: {ari_before_kmeans:.4f}, NMI: {nmi_before_kmeans:.4f}")

# Relabeling K-Means
kmeans_relabel = relabel_clusters(true_labels, kmeans_labels)
ari_after_kmeans = adjusted_rand_score(true_labels, kmeans_relabel)
nmi_after_kmeans = normalized_mutual_info_score(true_labels, kmeans_relabel)
print(f"K-Means Setelah Relabeling - ARI: {ari_after_kmeans:.4f}, NMI: {nmi_after_kmeans:.4f}")

# Evaluasi sebelum relabeling untuk GMM
ari_before_gmm = adjusted_rand_score(true_labels, gmm_labels)
nmi_before_gmm = normalized_mutual_info_score(true_labels, gmm_labels)
print(f"GMM Sebelum Relabeling - ARI: {ari_before_gmm:.4f}, NMI: {nmi_before_gmm:.4f}")

# Relabeling GMM
gmm_relabel = relabel_clusters(true_labels, gmm_labels)
ari_after_gmm = adjusted_rand_score(true_labels, gmm_relabel)
nmi_after_gmm = normalized_mutual_info_score(true_labels, gmm_relabel)
print(f"GMM Setelah Relabeling - ARI: {ari_after_gmm:.4f}, NMI: {nmi_after_gmm:.4f}")

# Tampilkan perbandingan hasil sebelum & sesudah relabeling
print("\nPerbandingan K-Means Sebelum Relabeling:")
print(pd.crosstab(true_labels, kmeans_labels))
print("\nPerbandingan K-Means Setelah Relabeling:")
print(pd.crosstab(true_labels, kmeans_relabel))

print("\nPerbandingan GMM Sebelum Relabeling:")
print(pd.crosstab(true_labels, gmm_labels))
print("\nPerbandingan GMM Setelah Relabeling:")
print(pd.crosstab(true_labels, gmm_relabel))
df.to_csv("processed_winequality.csv", index=False)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, homogeneity_score, completeness_score, v_measure_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load dataset
df = pd.read_csv('winequality-red.csv')
X = df.drop(columns=['quality'])  # Fitur
y = df['quality']  # Label asli

# Reduksi dimensi dengan PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Klasterisasi dengan K-Means dan GMM
n_clusters = len(y.unique())
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_pca)

gmm = GaussianMixture(n_components=n_clusters, random_state=42)
gmm_labels = gmm.fit_predict(X_pca)

# Relabeling berdasarkan kemiripan dengan kelas asli
relabel_map = {}
for cluster in range(n_clusters):
    mode_label = y[kmeans_labels == cluster].mode()[0]
    relabel_map[cluster] = mode_label

kmeans_labels_relabel = np.vectorize(relabel_map.get)(kmeans_labels)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_cluster, X_test_cluster, y_train_cluster, y_test_cluster = train_test_split(
    X, kmeans_labels_relabel, test_size=0.2, random_state=42)

# Define classifiers
classifiers = {
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier()
}

# Iterate over classifiers
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    clf.fit(X_train_cluster, y_train_cluster)
    y_pred_cluster = clf.predict(X_test_cluster)

    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    print(f"{name} (Clustered) Accuracy: {accuracy_score(y_test_cluster, y_pred_cluster):.4f}")
    print(classification_report(y_test_cluster, y_pred_cluster))
    print("="*50)

# Tampilkan hasil evaluasi
results_df = pd.DataFrame(results).T
print(results_df)